### ISSUE TITLE
ThreadSafety/InstanceVariableInClassMethod erroring on class variables that are determinisitic 

### ISSUE THREAD

**Issue by KieranP** [rubocop/rubocop-thread_safety#63]
Consider the following:

```ruby
module Objects
  class Base < GraphQL::Schema::Object
    def self.policy(policy)
      @policy ||= policy  # Cop fails here
    end
  end

  class User < Base
    policy :show_user?
    ...
  end

  class Post < Base
    policy :show_post?
    ...
  end
end

Objects::User.policy => :show_user?
Objects::Post.policy => :show_post?
```

In the above case, policy will always be deterministic. If multiple threads access Objects::User, it will always be :show_user?.

Is there a way for the `ThreadSafety/InstanceVariableInClassMethod` cop to detect this sort of use case (i.e. static value)?

Or is there still thread safety issues with setting the same value?

Changing to this works bit is a bit odd:

```ruby
def policy(policy)
  Thread.current["#{name}.policy"] ||= policy
end
```

**Comment by mikegee** [comment]
I don't see a class method in the code you have shown. Can you also post how the cop fails? Which line does it point to?

**Comment by KieranP** [comment]
@mikegee Sorry, have fixed up above code sample, fixed the class method and added comment

**Comment by mikegee** [comment]
I'm still slightly distracted by those last two lines where you can call, for instance `Objects::User.policy` with no arguments, but that's probably not why we're here.

This pattern look like something that has come up a few times on this project. RuboCop can't know about all of the callers of a given method. That class method definition is certainly mutating a shared state. But you know that you only ever call that method once at class-definition time and never mutate the state at "runtime". I would mark that method safe by telling RuboCop to disable the cop either with an inline comment or via the config file.

Another variation on that advice is to extract all those boot-time mutations to someplace like `config/initializers/setup_policies.rb`. That way a line in the config to ignore that one file makes more sense because that's all that file does.

**Comment by viralpraxis** [comment]
I agree with @mikegee. This is similar to ActiveSupport's `class_attribute`, which works well as long as its value isn’t mutated at runtime. Since static analysis can’t determine whether that’s happening, we mark each macro as an offense by default.
